### ISSUE TITLE
"友站連結"頁面. styling

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#143]
連到

1. [自學生經驗匯流](https://galacticproject.notion.site/d7477db76ecd4ff3b453a39ba21d97ef)

**Comment by leechiuhui** [comment]
Teacher, since you have completed the Friend Links section at https://www.alearn.org.tw/%E5%8F%8B%E7%AB%99%E9%80%A3%E7%B5%90, and I noticed that https://github.com/3dw/start-learn the Start-Learn repository on GitHub is under construction, do you think this issue ＃ could  be  completed by linkink to https://github.com/3dw/start-learn Start-Learn ? Additionally, I would like to know more about the plans for the Start-Learn repository. Thank you, Teacher."

**Comment by bestian** [comment]
start-learn是用來覆蓋
https://map.alearn.org.tw
的

因為
https://www.github.com/3dw/automap
已經無法更新了

start-learn我會負責慢慢建構
和auto20-next是獨立的專案

"友站連結"頁面是建議在各專案都放上, 彼此link起來

**Comment by bestian** [comment]
well done.

**Comment by leechiuhui** [comment]
done.
<img width="493" alt="截圖 2024-07-16 上午11 58 28" src="https://github.com/user-attachments/assets/7c65db72-fb79-47a2-b129-bf0ffbda147d">
