### ISSUE TITLE
PWA登入後看不到任何資料

### ISSUE THREAD

**Issue by bestian** [3dw/auto20-next#144]
好像是有bug
我用Google登入之後，結果一直卡在loader

作業系統： iOS
瀏覽方式： P W A (一般網頁瀏覽是正常)

![image](https://github.com/user-attachments/assets/21d61953-597b-4420-9254-62e6c1de6fe6)

**Comment by leechiuhui** [comment]
I encountered this situation two weeks ago as well, but it was resolved after reloading. I just recorded various scenarios and error messages, and plan to handle it on Tuesday.[https://www.loom.com/share/3b486cacb04d4f8daee03e08aee1b585](https://www.loom.com/share/3b486cacb04d4f8daee03e08aee1b585)

![image](https://github.com/user-attachments/assets/e6be0f7b-d085-4d8d-b194-acac1c5ef786)

**Comment by leechiuhui** [comment]
2024-07-24：not only did the phone keep loading, but the computer's Google Chrome did as well. However, after reloading, the login process worked fine. Initially, it seems that this issue occurs because there is no UID data during the first login attempt, causing the system to hang. Starting today, I will begin learning how to observe the data in local storage.
<img width="1510" alt="截圖 2024-07-24 晚上9 34 30" src="https://github.com/user-attachments/assets/8350b2a7-8eeb-4469-a483-41f015a54794">

**Comment by leechiuhui** [comment]
1Temporarily remove the loader
2The Map also looks weird when not logged in
3Immediately after logging out, the Map still shows the logged-in state

**Comment by bestian** [comment]
> Immediately after logging out, the Map still shows the logged-in state

logout之後，auth token還在，所有旗幟還是可以讀，應該是正常的.
login的部份修好了.

**Comment by leechiuhui** [comment]
I initially wanted to debug it slowly by myself, but my skills are indeed not sufficient. I am currently studying the teacher's  solution, which is also a great way to improve my skill. Thank you, teacher.
